# compiler
CC=cc
# delete files
RM=rm -rf
# create directory
MKDIR=-mkdir -p
# binary file directory
BIN_DIR=../bin/chapter-2

.PHONY: build

# make build
build:
	$(MKDIR) $(BIN_DIR)
	@echo Starting compile chapter 2 codes...

.PHONY: clean

clean:
	$(RM) $(BIN_DIR)
