# c flag
CFLAG=-std=c99 -Wall
# delete files
RM=rm -rf
# create directory
MKDIR=-mkdir -p
# binary file directory
BIN_DIR=../bin/chapter-13

# make build
build:
	$(MKDIR) $(BIN_DIR)
	@echo Compiling chapter 13 codes...

.PHONY: clean

clean:
	$(RM) $(BIN_DIR)
