# compiler
CC=cc -std=c99 -Wall
# delete files
RM=rm -rf
# create directory
MKDIR=-mkdir -p
# binary file directory
BIN_DIR=../bin/chapter-5

.PHONY: build

# make build
build:
    $(MKDIR) $(BIN_DIR)
    @echo Starting compile chapter 5 codes...
    

.PHONY: clean

clean:
    $(RM) $(BIN_DIR)
